### ISSUE TITLE
Description environment in the marginnotes

### ISSUE THREAD

**Issue by zaript** [michal-h21/tufte-tex4ht#1]
Thank you for this config, it works well. I would like to have some list-like behaviour in the marginnotes, or in the captions. In latex, using description environment in marginnotes works, but in html output the list ends up in the body text. Could you suggest a fix please?

**Comment by michal-h21** [comment]
I can take a look at this next week. Could you please provide a MWE that I can test?

**Comment by zaript** [comment]
Thank you. 
I have tested with this modification of the sample.tex in this repo:

```
\documentclass[]{tufte-book}
\usepackage{kantlipsum}
\usepackage{url}
\usepackage{graphicx}
\usepackage{csquotes}
\begin{document}
\title{Sample Document}
\author{Michal Hoftich}
\maketitle
\tableofcontents
\section{Introduction}

Some text.
\marginnote{
    Should be in margin.

    Should be in margin.
}

Description environment should be part of the margin note:
\marginnote{
    Should be in margin.
    \begin{description}
        \item Should be in margine.
        \item Should be in margine.
    \end{description}
}
\bibliography{sample-handout}
\bibliographystyle{plainnat}

\end{document}
```

**Comment by michal-h21** [comment]
Thanks for the MWE. The problem is that margin notes as used by Tufte CSS are meant only for smaller texts, they aren't designed to contain paragraphs or any lists. For that, you can use the `marginfigure` environment instead:

```
\documentclass[]{tufte-book}
\usepackage{kantlipsum}
\usepackage{url}
\usepackage{graphicx}
\usepackage{csquotes}
\begin{document}
\title{Sample Document}
\author{Michal Hoftich}
\maketitle
\tableofcontents
\section{Introduction}

Some text.
\begin{marginfigure}
    Should be in margin.

    Should be in margin.
\end{marginfigure}

Description environment should be part of the margin note:
\begin{marginfigure}
    Should be in margin.
    \begin{description}
      \item[item 1] Should be in margine.
      \item[item 2] Should be in margine.
    \end{description}
\end{marginfigure}
\bibliography{sample-handout}
\bibliographystyle{plainnat}

\end{document}

```

**Comment by zaript** [comment]
Thank you! The marginfigure does indeed allow for lists to be included. 

P.S. Do you know if it is possible to make marginefigure anchor at the top/bottom, rather than at the middle?

**Comment by michal-h21** [comment]
I think it floats more or less at the place where you used it in the text, and it isn't possible to change it :/
